version: "3.3"
services:
  push:
    entrypoint: ws push_server --host 0.0.0.0
    image: bsergean/ws:10.5.7

  autoroute:
    image: ${DOCKER_REPO}/autoroute-csharp:build
    entrypoint: dotnet run
    depends_on:
      - push
