version: "3.3"
services:
  push:
    entrypoint: ws push_server --host 0.0.0.0
    image: ${DOCKER_REPO}/ws:build

  autoroute:
    image: ${DOCKER_REPO}/autoroute-libwebsockets:build
    entrypoint: /usr/bin/autoroute
    depends_on:
      - push
