version: "3.3"
services:
  push:
    entrypoint: ws push_server --host 0.0.0.0
    image: bsergean/ws:10.3.4

  autoroute:
    image: ${DOCKER_REPO}/autoroute-libwebsockets:build
    entrypoint: /usr/bin/autoroute push
    depends_on:
      - push
