version: "3.3"
services:
  push:
    entrypoint: ws push_server --host 0.0.0.0
    image: bsergean/ws:10.3.4

  autoroute:
    entrypoint: ws autoroute ws://push:8008
    image: bsergean/ws:10.5.6
    depends_on:
      - push
