version: "3.3"
services:
  push:
    entrypoint: ws push_server --host 0.0.0.0
    image: ${DOCKER_REPO}/ws:build

  autoroute:
    entrypoint: python3 /usr/bin/autoroute.py --msg_count 100000 --url ws://push:8008
    image: ${DOCKER_REPO}/autoroute-python-websockets:build
    depends_on:
      - push
    environment:
      - PYTHONUNBUFFERED=1
