version: "3.3"
services:
  push:
    entrypoint: ws push_server --host 0.0.0.0
    image: bsergean/ws:10.5.7

  autoroute:
    entrypoint: python3 /usr/bin/autoroute.py --msg_count 1000000 --url ws://push:8008
    image: ${DOCKER_REPO}/autoroute-python-websocket_client:build
    depends_on:
      - push
    environment:
      - PYTHONUNBUFFERED=1
