version: "3.3"
services:
  push:
    entrypoint: ws push_server --host 0.0.0.0
    image: bsergean/ws:10.5.7

  autoroute:
    entrypoint: /app/target/release/autoroute
    image: ${DOCKER_REPO}/autoroute-rust:build
    depends_on:
      - push
