version: "3.3"
services:
  push:
    entrypoint: ws push_server --host 0.0.0.0
    image: bsergean/ws:10.3.4

  autoroute:
    entrypoint: cargo run --release
    image: ${DOCKER_REPO}/autoroute-rust:build
    depends_on:
      - push
