version: "3.3"
services:
  push:
    entrypoint: ws push_server --host 0.0.0.0
    image: ${DOCKER_REPO}/ws:build

  autoroute:
    entrypoint: node /usr/bin/autoroute.js ws://push:8008 100000
    image: ${DOCKER_REPO}/autoroute-node:build
    depends_on:
      - push
