version: "3.3"
services:
  push:
    entrypoint: ws push_server --host 0.0.0.0
    image: bsergean/ws:10.5.7

  autoroute:
    entrypoint: node /usr/bin/autoroute.js ws://push:8008 1000000
    image: ${DOCKER_REPO}/autoroute-node:build
    depends_on:
      - push
