version: "3.3"
services:
  push:
    entrypoint: ws push_server --host 0.0.0.0
    image: ${DOCKER_REPO}/ws:build

  autoroute:
    entrypoint: go run main.go ws://push:8008/1000000
    image: ${DOCKER_REPO}/autoroute-go:build
    depends_on:
      - push
